GuildFoundTools = GuildFoundTools or {}

GuildFoundTools.MESSAGE_TYPE = {
	GROUP_CREATE = "GROUP_CREATE",
	GROUP_EDIT = "GROUP_EDIT",
	GROUP_REMOVE = "GROUP_REMOVE",
	GROUP_SIGNUP = "GROUP_SIGNUP",
	GROUP_LEAVE = "GROUP_LEAVE",
	GROUP_MEMBERS_SYNC = "GROUP_MEMBERS_SYNC",
	GROUP_LIST_REQUEST = "GROUP_LIST_REQUEST",
	GROUP_LIST_ANSWER = "GROUP_LIST_ANSWER",
	PROFESSION_QUERY = "PROFESSION_QUERY",
	PROFESSION_ANSWER = "PROFESSION_ANSWER",
}
