local L = LibStub("AceLocale-3.0"):NewLocale("ClassicGuildTools", "deDE")
if not L then return end

-- General
L["AddonTitle"] = "Classic Guild Tools"
L["MinimapTooltip"] = "Klicken um das Fenster zu öffnen"
L["NotInGuild"] = "Du bist in keiner Gilde."

-- Roles
L["TANK"] = "Tank"
L["HEAL"] = "Heiler"
L["DD"] = "Damage Dealer"
L["BeginnerFriendly"] = "Neulinge willkommen"
L["BeginnerFriendlyTooltip"] = "Zeigt an, dass du neue Spieler in deiner Gruppe willkommen heißt und bereit bist, ihnen als Guide zu helfen."

-- UI Tabs
L["TabGroupBrowser"] = "Gruppenbrowser"
L["TabCreateGroup"] = "Gruppe erstellen"
L["TabMyGroup"] = "Meine Gruppe"
L["TabProfessions"] = "Berufe"
L["TabProfessionsDisabled"] = "Bald verfügbar"

-- Group Browser
L["NoGroupsAvailable"] = "Keine Gruppen vorhanden.\nErstelle eine Gruppe oder warte auf Gildenmitglieder."
L["ButtonSignUp"] = "Anmelden"
L["ButtonLeave"] = "Verlassen"
L["ContextMenuSendMessage"] = "Nachricht senden"
L["ContextMenuInvitePlayer"] = "Spieler einladen"
L["TooltipMembersHeader"] = "Mitglieder:"
L["TooltipMembersSummary"] = "Mitglieder: |cffffffff%d/%s (%d/%d/%d)|r"

-- Create/Edit Group
L["LabelCategory"] = "Kategorie:"
L["LabelDungeonRaid"] = "Dungeon/Raid:"
L["DropdownSelect"] = "-- Wählen --"
L["DungeonsSelected"] = "ausgewählt"
L["TabCreateGroupDisabled"] = "Nur der Gruppenleiter kann eine Gruppe erstellen."
L["ValidationNoDungeonSelected"] = "Kein Dungeon ausgewählt"
L["ValidationNoRaidSelected"] = "Kein Raid ausgewählt"
L["LabelDescription"] = "Beschreibung (optional):"
L["LabelMaxMembers"] = "Max. Mitglieder:"
L["ButtonCreate"] = "Erstellen"
L["ButtonRemoveGroup"] = "Gruppe entfernen"
L["ButtonEdit"] = "Bearbeiten"
L["ButtonBack"] = "Zurück"
L["ButtonSave"] = "Speichern"
L["NoSignupsYet"] = "Noch keine Anmeldungen für deine Gruppe vorhanden.\nSobald sich Gildenmitglieder anmelden, erscheinen sie hier."
L["MemberOfGroup"] = "Du bist in der Gruppe von %s."

-- Applicants
L["ButtonWithdraw"] = "Zurückziehen"
L["ButtonAccept"] = "Annehmen"
L["ButtonDecline"] = "Ablehnen"
L["ApplicantsHeader"] = "Bewerber:"
L["NoApplicantsYet"] = "Noch keine Bewerber."
L["ApplicationPending"] = "Bewerbung ausstehend..."

-- Role Selection Popup
L["SelectRoleTitle"] = "Rolle wählen"
L["SelectRolePrompt"] = "Welche Rolle möchtest du spielen?"

-- Invite Confirmation
L["InviteConfirmTitle"] = "Gruppeneinladung"
L["InviteConfirmText"] = "%s möchte dich in die Gruppe einladen."
L["InviteConfirmLeaveWarning"] = "Du verlässt deine aktuelle Gruppe wenn du akzeptierst."
L["InviteDeclinedMessage"] = "%s hat die Einladung abgelehnt."
L["ButtonAcceptInvite"] = "Beitreten"
L["ButtonDeclineInvite"] = "Ablehnen"

-- Chat Messages
L["AlreadyHaveGroup"] = "Du hast bereits eine Gruppe erstellt."
L["GroupRemovedJoinedOther"] = "Deine Gruppe wurde entfernt, da du einer anderen Gruppe beigetreten bist."

-- Professions
L["ButtonQueryProfessions"] = "Berufe abfragen"
L["QuerySent"] = "Abfrage gesendet..."
L["ResponsesReceived"] = "%d Antworten erhalten"
L["OpenProfessionWindow"] = "Berufsfenster öffnen\num Rezepte zu teilen"
L["LoadingItem"] = "Lade... (Item %d)"
L["SearchPlaceholder"] = "Suchen..."
L["SendMessageTo"] = "Nachricht an %s senden"
L["SettingsShowOnlyOnline"] = "Nur Online-Spieler anzeigen"
L["AllProfessions"] = "Alle Berufe"
L["NoRecipesFound"] = "Keine Rezepte gefunden."
L["ColumnItem"] = "Item"
L["ColumnPlayers"] = "Spieler"
L["You"] = "Du"
L["ProfessionAlchemy"] = "Alchimie"
L["ProfessionBlacksmithing"] = "Schmiedekunst"
L["ProfessionEnchanting"] = "Verzauberkunst"
L["ProfessionEngineering"] = "Ingenieurskunst"
L["ProfessionLeatherworking"] = "Lederverarbeitung"
L["ProfessionTailoring"] = "Schneiderei"
L["ProfessionCooking"] = "Kochkunst"
L["ProfessionFirstAid"] = "Erste Hilfe"
L["ProfessionJewelcrafting"] = "Juwelenschleifen"
L["ProfessionInscription"] = "Inschriftenkunde"
L["ProfessionHerbalism"] = "Kräuterkunde"
L["ProfessionMining"] = "Bergbau"
L["ProfessionSkinning"] = "Kürschnerei"

-- Dungeons
L["DungeonRagefireChasm"] = "Ragefireabgrund"
L["DungeonWailingCaverns"] = "Die Höhlen des Wehklagens"
L["DungeonTheDeadmines"] = "Die Todesminen"
L["DungeonShadowfangKeep"] = "Burg Schattenfang"
L["DungeonBlackfathomDeeps"] = "Tiefschwarze Grotte"
L["DungeonTheStockade"] = "Das Verlies"
L["DungeonGnomeregan"] = "Gnomeregan"
L["DungeonRazorfenKraul"] = "Kral der Klingenhauer"
L["DungeonScarletMonasteryGraveyard"] = "Das Scharlachrote Kloster - Friedhof"
L["DungeonScarletMonasteryLibrary"] = "Das Scharlachrote Kloster - Bibliothek"
L["DungeonScarletMonasteryArmory"] = "Das Scharlachrote Kloster - Waffenkammer"
L["DungeonScarletMonasteryCathedral"] = "Das Scharlachrote Kloster - Kathedrale"
L["DungeonRazorfenDowns"] = "Hügel der Klingenhauer"
L["DungeonUldaman"] = "Uldaman"
L["DungeonZulFarrak"] = "Zul'Farrak"
L["DungeonMaraudon"] = "Maraudon"
L["DungeonTheTempleOfAtalHakkar"] = "Der Tempel von Atal'Hakkar"
L["DungeonBlackrockDepths"] = "Schwarzfelstiefen"
L["DungeonLowerBlackrockSpire"] = "Untere Schwarzfelsspitze"
L["DungeonUpperBlackrockSpire"] = "Obere Schwarzfelsspitze"
L["DungeonDireMaulEast"] = "Düsterbruch Ost"
L["DungeonDireMaulWest"] = "Düsterbruch West"
L["DungeonDireMaulNorth"] = "Düsterbruch Nord"
L["DungeonScholomance"] = "Scholomance"
L["DungeonStratholmeMainGate"] = "Stratholme - Haupttor"
L["DungeonStratholmeServiceGate"] = "Stratholme - Dienstboteneingang"

-- Raids
L["RaidMoltenCore"] = "Der Geschmolzene Kern"
L["RaidOnyxiasLair"] = "Onyxias Hort"
L["RaidBlackwingLair"] = "Pechschwingenhort"
L["RaidZulGurub"] = "Zul'Gurub"
L["RaidRuinsOfAhnQiraj"] = "Ruinen von Ahn'Qiraj"
L["RaidTempleOfAhnQiraj"] = "Tempel von Ahn'Qiraj"
L["RaidNaxxramas"] = "Naxxramas"
